name: "release"

on:
    push:
        branches:
            -  main

jobs:
    release:
        name: release
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@3
            - name: node
              uses: actions/setup-node@3
              with:
                  node-version: 12
                  registry-url: https://registry.npmjs.org
            - run: npm run build
            - name: publish
              run: npm publish --access public
              working-directory: dist/ioco-framework
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
